#!/bin/bash
# Linux (requires lmsensors package)
#messg="$(sensors | grep temp1 | awk '{print $2}' | tr -d °)"

# Mac (requires https://github.com/lavoiesl/osx-cpu-temp)
messg="$(osx-cpu-temp)"

if [ -z "$messg" ];
    then
        echo "?"
    else
        echo "$messg"
fi
