#!/bin/bash
gmail_login="YOUR_USERNAME"
gmail_password="YOUR_PASSWORD"

messg="$(wget --secure-protocol=TLSv1 --timeout=3 -t 1 -q --no-check-certificate -O - https://${gmail_login}:${gmail_password}@mail.google.com/mail/feed/atom \
    | grep 'fullcount' \
    | sed -e 's/.*<fullcount>//;s/<\/fullcount>.*//' 2>/dev/null)"

if [ -z "$messg" ]; then
        echo "?"
else
        echo "$messg"
fi
